name: Deploy to DEV

on:
  pull_request:
    types: [closed]
    branches:
      - main
    

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deployment step
      run: echo "Deploying to dev..."
  Promote_QA:
    needs: deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Promote to QA
      run: echo "Promoting to QA..."
