name: Deploy to QA

on:
  workflow_run:
    workflows: ["Deploy to DEV"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deployment step
      run: echo "Deploying to qa..."
    
  Promote_SIT:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: Promote to SIT
      run: echo "Promoting to SIT..."
