name: Deploy to SIT

on:
  workflow_run:
    workflows: ["Deploy to QA"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: sit
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deployment step
      run: echo "Deploying to sit..."
  
  Promote_SIT:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: sit
    steps:
    - name: Promote to Staging
      run: echo "Promoting to STAGING..."