name: Deploy to DEV

on:
  push:
    branches:
      - main
    

jobs:
  Deploy_Dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deployment step
      run: echo "Deploying to dev..."
    - name: Health check step
      run: echo "Health check for dev..."
  Promote_QA:
    needs: Deploy_Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Promote to QA
      run: echo "Promoting to QA..."
